application: coolmetronome
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /sound
  static_dir: static/sound

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)

- url: /.*
  script: main.py
